name: Build & Deploy
on:
  push:
    branches:
      - stage
      - prod

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file
        run: |
          echo 'APP_NAME="${{ secrets.APP_NAME }}"' >> .env
          echo 'BRANCH_NAME="${{ github.ref_name }}"' >> .env
          echo 'DOMAIN_NAME="${{ secrets.DOMAIN_NAME }}"' >> .env
          echo 'FULL_NAME="${{ secrets.FULL_NAME }}"' >> .env
          echo 'ORIGIN="${{ secrets.ORIGIN }}"' >> .env
          echo 'ADMIN="${{ secrets.ADMIN }}"' >> .env
          echo 'ACCESS_SECRET="${{ secrets.ACCESS_SECRET }}"' >> .env
          echo 'REFRESH_SECRET="${{ secrets.REFRESH_SECRET }}"' >> .env
          echo 'SESSION_SECRET="${{ secrets.SESSION_SECRET }}"' >> .env
          echo 'ACCESS_TOKEN_DURATION="${{ secrets.ACCESS_TOKEN_DURATION }}"' >> .env
          echo 'DATABASE_URL="${{ secrets.DATABASE_URL }}"' >> .env
          echo 'CLOUDFLARE_SITE_KEY="${{ secrets.CLOUDFLARE_SITE_KEY }}"' >> .env
          echo 'CLOUDFLARE_SECRET_KEY="${{ secrets.CLOUDFLARE_SECRET_KEY }}"' >> .env
          echo 'FACEBOOK_CLIENT_ID="${{ secrets.FACEBOOK_CLIENT_ID }}"' >> .env
          echo 'GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"' >> .env
          echo 'GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"' >> .env

      - name: Installing Dependencies
        run: npm install

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Building App
        run: npm run build

      - name: Deleting devDependencies
        run: npm prune --omit dev

      # ASSETS
      - name: Deploy Assets to S3 bucket
        run: aws s3 sync build/client/ s3://${{ secrets.APP_NAME }}-${{ github.ref_name }}-assets --delete

      # LAYER
      - name: Zip Node Modules
        run: zip -r node_modules.zip node_modules .env index.js

      - name: Deploy the node_modules.zip to layer bucket
        run: aws s3 cp node_modules.zip s3://${{ secrets.APP_NAME }}-${{ github.ref_name }}-layer

      - name: Publish Layer Version
        id: layer
        run: |
          layer_version=$(aws lambda publish-layer-version \
            --layer-name ${{ secrets.APP_NAME }}-${{ github.ref_name }}-layer \
            --content S3Bucket=${{ secrets.APP_NAME }}-${{ github.ref_name }}-layer,S3Key=node_modules.zip \
            --query 'LayerVersionArn' --output text)
            echo "version=${layer_version}" >> $GITHUB_OUTPUT

      # LAMBDA
      - name: Zip Build Package
        run: zip -r function.zip package.json build/server index.js .env

      - name: Deploy the function.zip to lambda function
        run: |
          aws lambda update-function-code \
          --function-name ${{ secrets.APP_NAME }}-${{ github.ref_name }} \
          --zip-file fileb://function.zip \
          --no-cli-pager

      # CONFIG
      - name: Wait for the function to be updated
        run: |
          aws lambda wait function-updated \
          --function-name ${{ secrets.APP_NAME }}-${{ github.ref_name }} \
          --no-cli-pager

      - name: Update the lambda function configuration
        run: |
          aws lambda update-function-configuration \
          --function-name ${{ secrets.APP_NAME }}-${{ github.ref_name }} \
          --layers "${{ steps.layer.outputs.version }}" \
          --no-cli-pager
